export const metadata = {
  title: 'Terms of Service - Aproject',
  description: 'Terms of Service for using the Aproject platform',
};

export default function TermsPage() {
  return (
    <div className="h-full overflow-y-auto">
      <div className="min-h-screen bg-gray-50">
        <div className="container mx-auto px-4 py-12 max-w-4xl">
          <div className="bg-white rounded-lg shadow-sm p-8 md:p-12">
            <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>

            <p className="text-gray-600 mb-8 italic">
              Last Updated: {new Date().toLocaleDateString('en-AU', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>

            <div className="space-y-8">
              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Introduction</h2>
                <p className="text-gray-700 leading-relaxed">
                  Welcome to Aproject (“we,” “our,” or “us”). By accessing or using our website (https://chatlima.com) and
                  services, including any AI-powered chat experiences, APIs, or related features (collectively, the “Platform”),
                  you agree to be bound by these Terms of Service (“Terms”). Please read these Terms carefully before using the Platform.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Definitions</h2>
                <ul className="space-y-2 text-gray-700">
                  <li className="flex items-baseline space-x-2">
                    <span className="font-medium">“Platform”</span>
                    <span>refers to the Aproject website, applications, APIs, and all related services.</span>
                  </li>
                  <li className="flex items-baseline space-x-2">
                    <span className="font-medium">“Content”</span>
                    <span>refers to prompts, messages, files, outputs generated by the Platform, and any other material available through the Platform.</span>
                  </li>
                  <li className="flex items-baseline space-x-2">
                    <span className="font-medium">“User”</span>
                    <span>refers to any individual or entity who accesses or uses the Platform.</span>
                  </li>
                  <li className="flex items-baseline space-x-2">
                    <span className="font-medium">“User Content”</span>
                    <span>refers to content submitted, uploaded, or provided by Users (e.g., prompts, files).</span>
                  </li>
                  <li className="flex items-baseline space-x-2">
                    <span className="font-medium">“AI Output”</span>
                    <span>refers to content generated by the Platform’s AI models in response to User inputs.</span>
                  </li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. Account Registration</h2>
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">3.1 Account Requirements</h3>
                    <p className="text-gray-700 mb-3">To use certain features, you must create an account by providing:</p>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Valid email address</li>
                      <li>Full name or organization name</li>
                      <li>Billing details (for paid features)</li>
                      <li>Any other information reasonably required to provide the services</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">3.2 Account Responsibilities</h3>
                    <p className="text-gray-700 mb-3">You agree to:</p>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Provide accurate, current, and complete information</li>
                      <li>Maintain the security of your credentials</li>
                      <li>Accept responsibility for all activity under your account</li>
                      <li>Promptly notify us of any unauthorized access or security incident</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">3.3 Eligibility</h3>
                    <p className="text-gray-700">
                      You must be at least 13 years old, or the minimum age required in your jurisdiction, to use the Platform.
                      If you are under the age of majority, you may only use the Platform under the supervision of a parent or legal guardian who agrees to these Terms.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Use of the Platform and Content</h2>
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">4.1 User Content</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>You retain ownership of your User Content.</li>
                      <li>You grant us a worldwide, non-exclusive, royalty-free license to use, host, store, reproduce, and display your User Content solely as necessary to operate, maintain, and improve the Platform.</li>
                      <li>You represent and warrant that you have all rights necessary to submit your User Content and that it does not infringe the rights of any third party or violate applicable law.</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">4.2 AI Output</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>AI Output may be inaccurate, incomplete, or reflect biases. You are responsible for independently verifying the accuracy and appropriateness of any AI Output before relying on it.</li>
                      <li>Subject to applicable law, and to the extent permitted by model and data provider terms, you may use AI Output for your permitted purposes. Do not imply endorsement or factual accuracy without verification.</li>
                      <li>You must not use AI Output to create, distribute, or facilitate harmful, illegal, or deceptive content, including but not limited to malware, fraud, or violations of privacy or intellectual property rights.</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">4.3 Acceptable Use</h3>
                    <p className="text-gray-700 mb-3">You agree not to:</p>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Use the Platform in violation of any applicable law or regulation</li>
                      <li>Submit or generate content that is illegal, harmful, or exploits minors</li>
                      <li>Infringe intellectual property or privacy rights</li>
                      <li>Reverse engineer, attempt to extract model weights, or misuse APIs</li>
                      <li>Bypass usage limits, rate limits, or security controls</li>
                      <li>Use the Platform for autonomous weapons, surveillance targeting individuals, or other high-risk uses without appropriate safeguards</li>
                    </ul>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Plans, Credits, Payments and Refunds</h2>
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">5.1 Pricing and Credits</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Prices and credit costs are listed on the Platform and may change at any time.</li>
                      <li>Taxes and fees may apply based on your location.</li>
                      <li>Usage may consume credits or incur charges per request or per feature.</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">5.2 Billing</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>By providing a payment method, you authorize us (and our processors) to charge applicable fees.</li>
                      <li>Subscriptions renew automatically until canceled, where applicable.</li>
                      <li>You are responsible for maintaining accurate billing information.</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">5.3 Refund Policy</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Unless required by law or expressly stated otherwise, purchases are non-refundable. If we publish a specific refund window for certain purchases, that policy will govern those purchases.</li>
                      <li>We may refuse refunds in cases of abuse, excessive chargebacks, or violation of these Terms.</li>
                    </ul>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Third-Party Services</h2>
                <p className="text-gray-700">
                  The Platform may use or integrate with third-party services (e.g., model providers, payment processors).
                  Your use of such services may be subject to the third parties’ terms and privacy policies. We are not responsible for third-party services, content, or practices.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Termination</h2>
                <p className="text-gray-700 mb-3">
                  We may suspend or terminate your access to the Platform at any time, with or without notice, including if you violate these Terms, engage in abusive or fraudulent activity, create security risks, or if we discontinue the Platform. You may stop using the Platform at any time. Upon termination, your right to access the Platform will cease, but certain provisions will survive as noted below.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Intellectual Property</h2>
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">8.1 Platform IP</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>The Platform and its underlying technology, software, interfaces, and designs are owned by us or our licensors and are protected by intellectual property laws.</li>
                      <li>Except for the rights expressly granted in these Terms, no rights are transferred to you, and all rights are reserved.</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">8.2 Feedback</h3>
                    <p className="text-gray-700">
                      If you provide feedback, ideas, or suggestions, you grant us a worldwide, perpetual, irrevocable, royalty-free license to use and exploit that feedback without restriction or compensation.
                    </p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Privacy</h2>
                <p className="text-gray-700">
                  Our collection and use of personal information is described in our Privacy Policy. By using the Platform, you consent to our data practices as described there. Do not submit personal or sensitive information that you do not want processed by AI systems.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Disclaimer of Warranties</h2>
                <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                  <li>The Platform is provided “as is” and “as available”.</li>
                  <li>We disclaim all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement.</li>
                  <li>We do not warrant that the Platform will be error-free, uninterrupted, secure, or that AI Output will be accurate or reliable.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Limitation of Liability</h2>
                <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                  <li>To the maximum extent permitted by law, we are not liable for indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, use, or goodwill.</li>
                  <li>Our total liability for any claims arising out of or relating to the Platform will not exceed the amounts paid by you to us in the twelve (12) months preceding the event giving rise to liability.</li>
                  <li>We are not responsible for User Content, AI Output, or third-party services, and you are solely responsible for your use of the Platform and reliance on AI Output.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Indemnification</h2>
                <p className="text-gray-700">
                  You agree to defend, indemnify, and hold harmless Aproject and its affiliates, officers, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising from or related to your use of the Platform, your User Content, or your violation of these Terms or applicable law.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">13. Governing Law and Dispute Resolution</h2>
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">13.1 Governing Law</h3>
                    <p className="text-gray-700">
                      These Terms are governed by the laws of Queensland, Australia, without regard to conflict of laws principles.
                    </p>
                  </div>
                  <div>
                    <h3 className="text-xl font-medium text-gray-900 mb-3">13.2 Dispute Process</h3>
                    <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                      <li>Parties will first attempt to resolve disputes informally within 30 days.</li>
                      <li>Subject to applicable law, disputes will be brought exclusively in the courts of Queensland, Australia, and the parties consent to personal jurisdiction there.</li>
                      <li>The prevailing party may recover reasonable legal fees and costs.</li>
                    </ul>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">14. Changes to Terms</h2>
                <p className="text-gray-700 mb-3">We may modify these Terms at any time by:</p>
                <ul className="list-disc list-inside space-y-1 text-gray-700 ml-4">
                  <li>Posting updated Terms on the Platform</li>
                  <li>Notifying users of material changes when appropriate</li>
                  <li>Continued use after changes constitutes acceptance</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">15. Contact Information</h2>
                <div className="bg-gray-50 p-6 rounded-lg">
                  <p className="text-gray-700 mb-4">For questions about these Terms, contact us at:</p>
                  <ul className="space-y-2">
                    <li className="flex items-center space-x-2">
                      <span className="text-gray-600">Email:</span>
                      <a href="mailto:getchatlima@gmail.com" className="text-blue-600 hover:text-blue-800">getchatlima@gmail.com</a>
                    </li>
                    <li className="flex items-center space-x-2">
                      <span className="text-gray-600">Website:</span>
                      <a href="https://chatlima.com" className="text-blue-600 hover:text-blue-800">https://chatlima.com</a>
                    </li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">16. Severability</h2>
                <p className="text-gray-700">
                  If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-4">17. Entire Agreement</h2>
                <p className="text-gray-700">
                  These Terms constitute the entire agreement between you and Aproject regarding your use of the Platform and supersede any prior agreements on this subject.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold text-gray-900 mb-2">18. Region-Specific Disclosures</h2>
                <p className="text-gray-700">
                  If required by local law, additional terms may apply and will be provided or referenced on the Platform.
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}